#
# Copyright (c) 2023 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
authors = { workspace = true }
categories = { workspace = true }
description = "Internal crate for zenoh."
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
name = "zenoh-pinned-deps-1-75"
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
base64ct = "=1.6.0"
generic-array = "=0.14.7"
home = "=0.5.9"
icu_normalizer = "=1.5.0"
indexmap = "=2.11.4"
libloading = "=0.8.9"
librocksdb-sys = "=0.17.1"
litemap = "=0.7.4"
lz4_flex = "=0.11.3"
nonempty-collections = "=0.3.1"
pest = "=2.8.0"
pest_derive = "=2.8.0"
pest_generator = "=2.8.0"
pest_meta = "=2.8.0"
potential_utf = "=0.1.0"
rocksdb = "=0.23.0"
serde_spanned = "=1.0.1"
serde_with = "=3.14.1"
serde_with_macros = "3.14.1"
static_init = "=1.0.3"
thread-priority = "=1.2.0"
time = "=0.3.41"
tinystr = "=0.8.0"
toml = "=0.9.6"
toml_datetime = "=0.7.1"
toml_parser = "=1.0.2"
toml_writer = "=1.0.2"
twox-hash = "=1.6.3"
zerofrom = "=0.1.5"

[package.metadata.cargo-machete]
ignored = [
  "base64ct",
  "generic-array",
  "home",
  "icu_normalizer",
  "indexmap",
  "librocksdb-sys",
  "litemap",
  "lz4_flex",
  "pest",
  "pest_derive",
  "pest_generator",
  "pest_meta",
  "potential_utf",
  "rocksdb",
  "serde_spanned",
  "serde_with",
  "serde_with_macros",
  "static_init",
  "time",
  "tinystr",
  "toml",
  "toml_datetime",
  "toml_parser",
  "toml_writer",
  "twox-hash",
  "zerofrom",
]
