[files]
extend-exclude = [
  # Ignore files containing hexa.
  "io/zenoh-transport/tests/*.rs",
  "zenoh/tests/authentication.rs",
  "zenoh/tests/open_time.rs",
]


[default.extend-words]
Closee = "Closee"         # Closee
closee = "closee"         # closee
controllen = "controllen" # From libc
mis = "mis"               # mismatch
thr = "thr"               # throughput
