#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
rust-version = "1.62.1"
name = "zenoh-link-serial"
version = "0.7.0-rc"
repository = "https://github.com/eclipse-zenoh/zenoh"
homepage = "http://zenoh.io"
authors = [
	"kydos <angelo@icorsaro.net>",
	"Julien Enoch <julien@enoch.fr>",
	"Olivier HÃ©cart <olivier.hecart@zettascale.tech>",
	"Luca Cominardi <luca.cominardi@zettascale.tech>",
	"Pierre Avital <pierre.avital@zettascale.tech>",
	"Gabriele Baldoni <gabriele.baldoni@zettascale.tech>"
]
edition = "2018"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming"]
description = "Internal crate for zenoh."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

async-std = { version = "=1.12.0", default-features = false, features = [
	"unstable",
	"tokio1",
] }
async-trait = "0.1.59"
futures = "0.3.25"
log = "0.4.17"
tokio = { version = "1.23.1", default-features = false, features = ["io-std", "macros", "net", "rt-multi-thread", "time", "io-util"] }
uuid = { version = "1.2.2", features = ["v4"] }
z-serial = "0.2.0"
zenoh-cfg-properties = { version = "0.7.0-rc", path = "../../../commons/zenoh-cfg-properties/" }
zenoh-collections = { version = "0.7.0-rc", path = "../../../commons/zenoh-collections/" }
zenoh-config = { version = "0.7.0-rc", path = "../../../commons/zenoh-config/" }
zenoh-core = { version = "0.7.0-rc", path = "../../../commons/zenoh-core/" }
zenoh-link-commons = { version = "0.7.0-rc", path = "../../zenoh-link-commons/" }
zenoh-protocol-core = { version = "0.7.0-rc", path = "../../../commons/zenoh-protocol-core/" }
zenoh-sync = { version = "0.7.0-rc", path = "../../../commons/zenoh-sync/" }
zenoh-util = { version = "0.7.0-rc", path = "../../../commons/zenoh-util/" }
