#
# Copyright (c) 2023 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
rust-version = { workspace = true }
name = "zenoh-shm"
version = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
authors = [
	"kydos <angelo@icorsaro.net>",
	"Luca Cominardi <luca.cominardi@zettascale.tech>",
	"Pierre Avital <pierre.avital@zettascale.tech>",
]
edition = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
description = "Internal crate for zenoh."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test = ["num_cpus"]

[dependencies]
async-trait = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
zenoh-result = { workspace = true }
zenoh-core = { workspace = true }
zenoh-macros = { workspace = true }
zenoh-buffers = { workspace = true }
rand = { workspace = true, features = ["std", "std_rng"] }
static_init = { workspace = true }
num-traits = { workspace = true }
num_cpus = { workspace = true, optional = true }
thread-priority = { workspace = true }
stabby = { workspace = true }
crossbeam-queue = { workspace = true }
crossbeam-channel = { workspace = true }
static_assertions = { workspace = true }
zerocopy = { workspace = true, features = ["derive"] }

[target.'cfg(unix)'.dependencies]
advisory-lock = { workspace = true }
nix = { workspace = true, features = ["fs", "mman"] }

[target.'cfg(windows)'.dependencies]
win-sys = { workspace = true }
winapi = { workspace = true }

[dev-dependencies]
libc = { workspace = true }

[build-dependencies]
cfg_aliases = "0.2.1"