# By default, retry a few times until pass the test within the specified timeout
[profile.default]
retries = 4
slow-timeout = { period = "60s", terminate-after = 2 }

# Run the following tests exclusively with longer timeout
[[profile.default.overrides]]
filter = """
test(=zenoh_session_unicast) |\
test(=zenoh_session_multicast) |\
test(=three_node_combination)
"""
threads-required = 'num-cpus'
slow-timeout = { period = "60s", terminate-after = 6 }
