# By default, retry a few times until pass the test within the specified timeout
[profile.default]
retries = 2
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.default.junit]
path = "junit.xml"

# Run the following tests exclusively with longer timeout
[[profile.default.overrides]]
filter = """
test(=zenoh_session_unicast) |
test(=zenoh_session_multicast) |
test(=zenoh_unicity_p2p) |
test(=zenoh_unicity_brokered) |
test(=transport_tcp_intermittent) |
test(=transport_tcp_intermittent_for_lowlatency_transport) |
test(=transport_unicast_quic_only_mutual_success) |
test(=transport_unicast_quic_only_server) |
test(=three_node_combination) |
test(=watchdog_alloc_concurrent) |
test(=header_check_memory_concurrent) |
test(=header_link_concurrent) |
test(=header_link_failure_concurrent) |
test(=zenoh_querier_matching_status)
"""
slow-timeout = { period = "60s", terminate-after = 6 }
threads-required = 'num-cpus'
