#
# Copyright (c) 2023 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
rust-version = { workspace = true }
name = "zenoh-keyexpr"
version = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
description = "Internal crate for zenoh."

[features]
default = ["std"]
std = ["zenoh-result/std", "dep:schemars"]
internal = []
unstable = []
js = ["getrandom/js"]

[dependencies]
keyed-set = { workspace = true }
rand = { workspace = true, features = ["alloc", "getrandom"] }
schemars = { workspace = true, optional = true }
serde = { workspace = true, features = ["alloc"] }
token-cell = { workspace = true }
zenoh-result = { workspace = true }
# NOTE: getrandom needs to be explicitly added here in order to enable the `js` feature when compiling the rand crate to WASM
# more information: https://docs.rs/getrandom/latest/getrandom/#webassembly-support 
getrandom = { workspace = true }

[target.'cfg(not(features = "std"))'.dependencies]
hashbrown = { workspace = true }

# NOTE: May cause problems when testing no_std stuff. Check this tool: https://docs.rs/crate/cargo-no-dev-deps/0.1.0
[dev-dependencies]
ahash = { workspace = true, default-features = true }
criterion = { workspace = true }
lazy_static = { workspace = true }
rand = { workspace = true, features = ["default"] }

[[bench]]
name = "keyexpr_tree"
harness = false

# NOTE: for the above reason, we need to explicitly ignore getrandom in the CI because it's an indirect dependency which is not used directly by zenoh.
[package.metadata.cargo-machete]
ignored = ["getrandom"]